# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  image: ibmcom/pipeline-base-image:2.9
  script: |
    #!/usr/bin/env bash

    npm ci

deploy:
  image: ibmcom/pipeline-base-image:2.9
  script: |
    #!/usr/bin/env bash

    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi

    source scripts/deploy_setup.sh
    source scripts/deploy.sh

acceptance-test:
  image: ibmcom/pipeline-base-image:2.9
  script: |
    #!/usr/bin/env bash

    source /root/.nvm/nvm.sh
    npm ci
    export APP_URL=$(cat ../app-url)
    npm run acceptance-test
