# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  image: ibmcom/pipeline-base-image:2.9
  script: |
    #!/usr/bin/env bash

    npm ci

deploy:
  image: ibmcom/pipeline-base-image:2.6
  script: |
    #!/usr/bin/env bash

    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi

    source scripts/deploy_setup.sh
    source scripts/deploy.sh
    export DEPLOY_EXIT=$?
    source scripts/doi-publish-deploy.sh

acceptance-test:
  image: ibmcom/pipeline-base-image:2.9
  script: |
    #!/usr/bin/env bash

    source scripts/test.sh
    export EXIT=$?
    source scripts/doi-acceptance-test.sh
